### PR TITLE
Fix FromField Const instance; fixes #185

### LINKED ISSUE #185: Bug. FromField a => FromField (Const a b)
Hi,

There is a typo in Data.Csv.Conversion on line 814. It should be **fmap Const**, not fmap getConst, which creates an non-terminating loop.

Thanks for all the great work!

### PR DESCRIPTION
**Pull request by carymrobbins**
The old instance was causing a non-terminating loop.

### CODE REVIEW

**Comment by andreasabel** [comment]
Hej @carymrobbins, thanks for the PR!
- Could you please rebase your PR on the latest master, since I added a new CI there?
- Is there a test that could be added that would fail without your patch but succeed with it?

**Comment by carymrobbins** [comment]
Done! Added a test case that fails to terminate for the previous instance but succeeds with the new instance. I tried getting something working with `System.Timeout.timeout` but it doesn't seem to play nice with QuickCheck.

**Comment by andreasabel** [comment]
Excellent, thanks for the test @carymrobbins !

CI indicates that for GHC 7 you need another import for the test.  Would you be able to fix that?

**Comment by carymrobbins** [comment]
Just pushed a new commit which I think should fix it.

**Comment by andreasabel** [comment]
Thanks, @carymrobbins !
GitHub requires me to baby-sit its actions, I have to start them manually all the time.
But you can get quick feedback on your fork, e.g.: https://github.com/carymrobbins/cassava/actions/runs/1439662694

**Comment by andreasabel** [comment]
Great job, @carymrobbins !

**Pull request merged**
